name = "Mriya"
author = "mortuusars"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2013bd143e22a2ba196c93cc3fcca4563859219761daf42ae838804624d8b6ca"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
