name = "Mriya"
author = "mortuusars"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8c68e4ed4f6b9954a7050fbde706df19348357d0b09fa01073dd2876857b95c"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
