name = "Mriya"
author = "mortuusars"
version = "1.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "769f0ac7c44ec09161975631e245fd327ff55f3bf26dbe9652b7a59f8d9a239e"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
