name = "Mriya"
author = "mortuusars"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ee7f2d1c08bfdf34ded3541abee334ca819fe4502103b19b152ae064e598e2e"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
