name = "Mriya"
author = "mortuusars"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7bedc42a22adaf7d67846a884bece450801841c2e4cb9371aeb9d704d25d6cd"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
