name = "Mriya"
author = "mortuusars"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c493c25c76d207fc62ce92f849d2c5b9b1c81b146e708ccc9e128f412c70a381"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
