name = "Mriya"
author = "mortuusars"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16ba662722e6aaab3207b932eaf92391758926f31edf1e834e422fe728833496"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
