name = "Mriya"
author = "mortuusars"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0b0f9726bb52d1c908b61e0aad9938642ac354c61a5ecfaac2650e4c1e71ed1"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
