name = "Mriya"
author = "mortuusars"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19ba2880f8194cb02ff655dc9f145ee6c5f7cccadac86ec96e42b6e5ac1a0cce"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
