name = "Mriya"
author = "mortuusars"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6bc6dc6bceb3be687ce7c06d636b1620a64ef26b27e2e65b14127adaebb2807"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
