name = "Mriya"
author = "mortuusars"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c13020bfc030f89ad70b85eb0f80190bd552f0f3d79e546243fcae502d51b1bb"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
