name = "Mriya"
author = "mortuusars"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d45306bd2fbcbc29d2bd6df00514ae43f68845c4b71bc9ff3a1e3dea0d5b2797"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
